dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"
urlpatterns = [
    path("<slug:slug>", views.IndexView.as_view(), name="index"),
    path("activity/<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path(
        "activity/<int:activity_id>/do/",
        views.execute_activity,
        name="execute_activity",
    ),
    path(
        "activity/<int:activity_id>/do_as_team/",
        views.execute_activity_team,
        name="execute_activity_team",
    ),
    path("activity/create", views.ActivityCreateView.as_view(), name="create_activity"),
    path(
        "activity/<int:pk>/delete",
        views.ActivityDeleteView.as_view(),
        name="delete_activity",
    ),
    path(
        "activity/<int:pk>/update",
        views.ActivityUpdateView.as_view(),
        name="update_activity",
    ),
    path(
        "execution/create", views.ExecutionCreateView.as_view(), name="create_execution"
    ),
    path(
        "execution/create/<int:pk>",
        views.ExecutionCreateView.as_view(),
        name="create_execution",
    ),
    path(
        "execution/<int:pk>/update",
        views.ExecutionUpdateView.as_view(),
        name="update_execution",
    ),
    path(
        "execution/<int:pk>/delete",
        views.ExecutionDeleteView.as_view(),
        name="delete_execution",
    ),
    path("yaml", views.upload_file, name="upload_yaml"),
]

sprzatanie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("", include("dashboard.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns = [
        *urlpatterns,
    ] + debug_toolbar_urls()

dashboard/models.py
from django.db import models
from django.db.models.query import QuerySet
from datetime import date
from django.contrib.auth.models import User
import humanize


class Dashboard(models.Model):
    slug = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=200)
    # TODO default activity parameters

    # TODO group = Group()?


class Activity(models.Model):
    activity_name = models.CharField(max_length=200)
    date_created = models.DateField("date created", default=date.today, null=False)
    expected_period = models.DurationField("expected period")
    notes = models.TextField(
        "Notes or description of the activity", default="", blank=True
    )

    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE)
    EXECUTION_LIMIT = 10

    @property
    def last_entry(self):
        try:
            return self.associated_executions_by_date[0]
        except IndexError:
            return None

    def __str__(self, *args, **kwargs):
        return self.activity_name

    @property
    def priority(self):
        now = date.today()

        last_entry = self.last_entry

        if last_entry:
            last_date = last_entry.execution_date
        else:
            last_date = self.date_created
        return (now - last_date) / self.expected_period

    @property
    def associated_executions_by_date(self):
        return self.execution_set.order_by("-execution_date")[: self.EXECUTION_LIMIT]

    @property
    def associated_executions_by_date_more(self):
        return self.execution_set.order_by("-execution_date")[self.EXECUTION_LIMIT :]

    def execute(self, participant: User | list[User]):
        ex = Execution.objects.create(activity=self)
        if not isinstance(participant, QuerySet):
            participant = [participant]
        for p in participant:
            ex.executed_by.add(p)
        ex.save()


class Execution(models.Model):
    execution_date = models.DateField("date done", default=date.today)
    executed_by = models.ManyToManyField(User, blank=True)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)

    def __str__(self, *args, **kwargs):
        output = f"{self.activity.activity_name} done at {self.execution_date.strftime('%Y-%m-%d')}"
        if users := self.executed_by.all():
            output += " by " + humanize.natural_list(
                [
                    user.first_name if user.first_name else user.username
                    for user in users
                ]
            )
        return output

dashboard/forms.py
from django import forms


class UploadFileForm(forms.Form):
    file = forms.FileField()

dashboard/views.py
from .models import Activity, Execution, Dashboard
from datetime import timedelta, date

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from .forms import UploadFileForm
import yaml
import random


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = "dashboard/index.html"
    context_object_name = "activities"
    model = Activity

    @property
    def cutoff(self):
        try:
            cutoff = float(self.request.GET.get("priority", 1))
        except ValueError:
            cutoff = 1.0
        return cutoff

    def get_queryset(self, **kwargs):
        # queryset = super().get_queryset()
        d = Dashboard.objects.get(slug=self.kwargs["slug"])
        activities = d.activity_set.all()
        # priority is a property so I can't just .filter(priority__gte = self.cutoff)
        activities = list(
            filter(lambda activity: activity.priority >= self.cutoff, activities)
        )
        activities = sorted(
            activities, key=lambda activity: activity.priority, reverse=True
        )
        return activities

    def feeling_lucky(self) -> Activity | None:
        activities = self.model.objects.all()
        if not activities:
            return None
        priorities = [activity.priority for activity in activities]
        return random.choices(activities, weights=priorities)[0]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["dashboard"] = Dashboard.objects.get(slug=self.kwargs["slug"])
        context["priority"] = self.cutoff
        context["lucky"] = self.feeling_lucky()
        return context


class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Activity
    template_name = "dashboard/detail.html"


@login_required
def execute_activity(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    activity.execute(request.user)
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


@login_required
def execute_activity_team(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    activity.execute(User.objects.all())
    return HttpResponseRedirect(request.META.get("HTTP_REFERER", "/"))


class ActivityCreateView(LoginRequiredMixin, generic.CreateView):
    model = Activity
    fields = ["activity_name", "expected_period", "notes"]
    success_url = reverse_lazy("dashboard:index")


class ActivityUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Activity
    fields = ["activity_name", "expected_period", "notes"]

    def get_success_url(self):
        return reverse("dashboard:detail", args=[self.object.id])


class ActivityDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Activity
    # fields = ["activity_name", "expected_period", "notes"]

    def get_success_url(self):
        return reverse("dashboard:index")


class ExecutionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Execution
    fields = ["activity", "execution_date", "executed_by"]

    def get_success_url(self):
        return reverse("dashboard:detail", args=[self.object.activity.id])

    def get_initial(self):
        initial = super().get_initial()
        initial["execution_date"] = date.today()
        if (
            "pk" in self.kwargs
        ):  # no cov - TODO I don't know how to test it without doing something like selenium
            initial["activity"] = Activity.objects.get(pk=self.kwargs["pk"]).id
        return initial


class ExecutionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Execution
    # fields = ["executed_by"]

    def get_success_url(self):
        return reverse("dashboard:detail", args=[self.object.activity.id])


class ExecutionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Execution
    fields = ["execution_date", "executed_by"]

    def get_success_url(self):
        return reverse("dashboard:detail", args=[self.object.activity.id])


def parse_period(period):
    if period.endswith("w"):
        return timedelta(days=7 * int(period.strip("w")))
    elif period.endswith("d"):
        return timedelta(days=int(period.strip("d")))
    else:
        raise ValueError(f"Period must be d for days or w for weeks and not `{period}`")


def handle_uploaded_file(f):
    d = yaml.load(f, Loader=yaml.FullLoader)
    for activity_name, activity_dict in d.items():
        activity_period = parse_period(activity_dict["period"])
        if existing_activities := Activity.objects.filter(
            activity_name=activity_name,
        ):
            activity = existing_activities.get()
            if activity.expected_period != activity_period:
                raise ValueError(
                    f"Mismatch on expected period of {activity.activity_name}"
                )  # TODO how to handle this, actually?
        else:
            activity = Activity(
                activity_name=activity_name, expected_period=activity_period
            )
            activity.save()

        executions = []
        for execution_date in activity_dict["dates"]:
            if not Execution.objects.filter(
                activity=activity, execution_date=execution_date
            ):
                execution = Execution(
                    execution_date=execution_date,
                    activity=activity,
                )
                executions.append(execution)

        Execution.objects.bulk_create(executions)


def upload_file(request):
    if request.method == "POST":
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES["file"])
            return HttpResponseRedirect(reverse("dashboard:index"))
    else:
        form = UploadFileForm()
    return render(request, "dashboard/upload.html", {"form": form})

dashboard/templates/dashboard/activity_confirm_delete.html
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

dashboard/templates/dashboard/activity_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
<h1>Create an activity</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

dashboard/templates/dashboard/detail.html
{% load static %}
{% load display_extras %}
<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
<header>
    <h1>{{ activity.activity_name }}</h1>
</header>

<main>
    <p class="notice">
    Started {{ activity.date_created }}, expected to do every {{  activity.expected_period | naturaldelta }}
    </p>

{% if activity.notes %}
<aside>
    {{activity.notes}}
</aside>
{% endif %}


<span id="button_bar">
<form type="hidden" action="{% url 'dashboard:execute_activity' activity.id %}" method="post">
    {% csrf_token %}
    <input class="button" type="submit" value="✅">
</form>
<form type="hidden" action="{% url 'dashboard:execute_activity_team' activity.id %}" method="post">
    {% csrf_token %}
    <input class="button" type="submit" value="🧑‍🤝‍🧑">
</form>
<form type="hidden" action="{% url 'dashboard:create_execution' activity.id %}" method="get">
    <input class="button" type="submit" value="❔">
</form>
</span>

<ul>
{% for execution in activity.associated_executions_by_date %}
<li> {{ execution }}
    <a href="{% url 'dashboard:update_execution' execution.id %}">(edit)</a>
    <a href="{% url 'dashboard:delete_execution' execution.id %}">(delete)</a>
</li>
{% endfor %}
</ul>

{% if activity.associated_executions_by_date_more %}
  <details>
  <summary> {{ activity.associated_executions_by_date_more | length }} more...</summary>

<ul>
{% for execution in activity.associated_executions_by_date_more %}
<li> {{ execution }}
    <a href="{% url 'dashboard:update_execution' execution.id %}">(edit)</a>
    <a href="{% url 'dashboard:delete_execution' execution.id %}">(delete)</a>
</li>
{% endfor %}
</ul>
  </details>
{% endif %}


</main>
<footer>
    Logged in as {{ user.username }}</br>
    <a href={% url 'dashboard:update_activity' activity.id %}>Edit</a> or <a href={% url 'dashboard:delete_activity' activity.id %}>delete</a> this activity?
    <br/>
    <a href={% url 'dashboard:index' activity.dashboard.slug %}>Return to dashboard.</a>
</footer>

dashboard/templates/dashboard/execution_confirm_delete.html
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

dashboard/templates/dashboard/execution_form.html
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
<h1>Edit execution</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

dashboard/templates/dashboard/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

<header>
    <h1>{{ dashboard.name }}</h1>
</header>
<main>

<div>
    <form>
        <label for="priority">Priority cut-off:</label>
        <input id="priority" min="0" max="1" step="0.05" value = "{{ priority }}" name="priority">
        <input id="filter-btn" type="submit" value="Filter">
    </form>
    <a href="{% url 'dashboard:index' dashboard.slug %}?priority=0.0">
        <input class="button" type="submit" value ="Show all">
    </a>
</div>
{% if activities %}


    <table>
    <tr>
        <th>Co?</th>
        <th>Okres</th>
        <th>Ostatnio</th>
        <th>Ile wpisów</th>
        <th>Priorytet</th>
        <th></th>
    </tr>
    {% for activity in activities %}
    <tr>
        <td id="activity_name">
            <a href="{% url 'dashboard:detail' activity.id %}">{{ activity.activity_name }}</a>
        </td>
        <td id="expected_period">
            {{ activity.expected_period.days }}d
        </td>
        <td id="last_execution_date"> {{ activity.last_entry.execution_date | date:"Y-m-d" }} </td>
        <td id="execution_count"> {{ activity.execution_set.count }} </td>
        <td id="priority"> {{ activity.priority | floatformat:-1 }} </td>
        <td id="done_button">
            <span id="button_bar">
                <form type="hidden" action="{% url 'dashboard:execute_activity' activity.id %}" method="post">
                    {% csrf_token %}
                    <input class="button" type="submit" value="✅">
                </form>
                <form type="hidden" action="{% url 'dashboard:execute_activity_team' activity.id %}" method="post">
                    {% csrf_token %}
                    <input class="button" type="submit" value="🧑‍🤝‍🧑">
                </form>
                <form type="hidden" action="{% url 'dashboard:create_execution' activity.id %}" method="get">
                    <input class="button" type="submit" value="❔">
                </form>
            </span>
        </td>
    </tr>
    {% endfor %}
    </table>
{% else %}
<p>No activities found at the current priority cutoff value. Try a lower one? </p>
{% endif %}
</main>

<footer>
    Logged in as {{ user.username }}</br>
    <a href="{% url 'dashboard:create_activity' %}">Create an activity?</a>
    <a href="{% url 'dashboard:upload_yaml' %}">Upload YAML?</a></br>
    {% if activities %}
      <a href="{% url 'dashboard:detail' lucky.id %}">Feelin' lucky?</a>
    {% endif %}
</footer>

dashboard/templates/dashboard/upload.html
{% load static %}
<link rel="stylesheet" href="{% static 'dashboard/style.css' %}">
<link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
<h1>Upload a YAML file</h1>

<form method="post"  enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value=" Upload">
</form>